### ISSUE TITLE
Incompatibility with better nether

### ISSUE THREAD

**Issue by Imcaam** [TeamMidnightDust/RoundTrees#4]
Hi, so I tried getting this mod to work with my client but it seems to crash with better nether . Here are the details

---- Minecraft Crash Report ----
// Don't do that.

Time: 11/12/21, 4:55 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'betternether'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:457)
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoClassDefFoundError: me/sargunvohra/mcmods/autoconfig1u/ConfigData
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1010)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:149)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at net.minecraft.class_2465.method_9530(class_2465.java:524)
	at net.minecraft.class_4970$class_4971.method_26172(class_4970.java:829)
	at net.minecraft.class_4970$class_4971.method_26218(class_4970.java:825)
	at net.minecraft.class_4970.method_9549(class_4970.java:344)
	at net.minecraft.class_4970$class_4971.method_26194(class_4970.java:840)
	at net.minecraft.class_4970$class_4971.method_26220(class_4970.java:836)
	at net.minecraft.class_4970.method_37403(class_4970.java:350)
	at net.minecraft.class_4970$class_4971.method_26234(class_4970.java:1041)
	at net.minecraft.class_3499.method_28054(class_3499.java:137)
	at net.minecraft.class_3499.method_15177(class_3499.java:712)
	at net.minecraft.class_3499.method_15183(class_3499.java:671)
	at paulevs.betternether.structures.StructureNBT.readStructureFromStream(StructureNBT.java:101)
	at paulevs.betternether.structures.StructureNBT.readStructureFromJar(StructureNBT.java:88)
	at paulevs.betternether.structures.StructureNBT.<init>(StructureNBT.java:30)
	at paulevs.betternether.structures.StructureWorld.<init>(StructureWorld.java:17)
	at paulevs.betternether.structures.decorations.StructureWartDeadwood.<clinit>(StructureWartDeadwood.java:13)
	at paulevs.betternether.biomes.NetherWartForest.<init>(NetherWartForest.java:36)
	at paulevs.betternether.registry.BiomesRegistry.<clinit>(BiomesRegistry.java:60)
	at paulevs.betternether.BetterNether.onInitialize(BetterNether.java:47)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 11 more
Caused by: java.lang.ClassNotFoundException: me.sargunvohra.mcmods.autoconfig1u.ConfigData
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	... 38 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:457)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1559057480 bytes (1486 MiB) / 2617245696 bytes (2496 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 5800X 8-Core Processor             
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 3.80
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: AMD Radeon RX 5700
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x731f
	Graphics card #0 versionInfo: DriverVersion=30.0.13031.1001
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.60
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.60
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 37813.59
	Virtual memory used (MB): 11664.11
	Swap memory total (MB): 21504.00
	Swap memory used (MB): 65.21
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		additionaladditions: Additional Additions 2.1.3
		adorn: Adorn 2.3.1+1.17.1
		advanced_runtime_resource_pack: Runtime Resource Pack 0.2.9
		amecs: Amecs 1.3.4+mc.1.17
		amecsapi: Amecs API 1.1.5+mc21w16a
		animal_feeding_trough: Animal Feeding Trough 1.0.2
		antiqueatlas: Antique Atlas 6.1.0-fabric-mc1.17.1
		aqupdgrizzly: Grizzly Bear mob 1.1.1
		arcanus: Arcanus 1.23
		architectury: Architectury 2.5.31
		armor-model-predicate: Armor Model Predicate 0.0.1
		artifacts: Artifacts 5.0.2+fabric
		autofish: Autofish 0.9.3
		awesomedungeon: Awesome Dungeon 1.1.2
		axesareweapons: Axes Are Weapons 1.4
		axolotlitemfix: Axolotl Item Fix 1.1.3
		basicshields: Basic Shields [Fabric] 1.1.1-1.17.1
		bclib: BCLib 0.5.0
		bebooks: Better Enchanted Books 1.2.11
		bedrockwaters: BedrockWaters 1.5.0+1.17.1
		betterdroppeditems: Better Dropped Items 1.3.0-1.17
		betterdungeons: YUNG's Better Dungeons 1.17-1.0.1
		betterend: Better End 0.12.2
		betterimpaling: Better Impaling 2.0.3
		bettermineshafts: YUNG's Better Mineshafts 1.17-1.0.1
		betternether: Better Nether 5.3.9
		betterstrongholds: YUNG's Better Strongholds 1.17-1.1.2
		betterthirdperson: Better Third Person 1.5.0
		blocktuner: BlockTuner 0.6.3
		blur: Blur (Fabric) 2.1.0
		boatcontainer: BoatContainer 1.0.3
		bookworm: Bookworm Library 1.0.0
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.3.2-1.17.1
		brewable_experience: Brewable Experience 1.1.1
		brokennametags: Broken Name Tags 1.0.1
		caelus: Caelus API 0.0.17-1.17
		campchair: Camp Chair 1.0.0
		cardinal-components: Cardinal Components API 3.1.1
		cardinal-components-base: Cardinal Components API (base) 3.1.1
		cardinal-components-block: Cardinal Components API (blocks) 3.1.1
		cardinal-components-chunk: Cardinal Components API (chunks) 3.1.1
		cardinal-components-entity: Cardinal Components API (entities) 3.1.1
		cardinal-components-item: Cardinal Components API (items) 3.1.1
		cardinal-components-level: Cardinal Components API (world saves) 3.1.1
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 3.1.1
		cardinal-components-util: Cardinal Components API (utilities) 3.1.1
		cardinal-components-world: Cardinal Components API (worlds) 3.1.1
		carrier: Carrier 1.8.1
		caves-and-cliffs-add-on-for-william-wythers-overhauled-overworld: Caves and Cliffs add-on for William Wythers Overhauled Overworld 1.4
		chalk: Chalk 1.0.2
		chat_heads: Chat Heads 0.5.1
		cherishedworlds: Cherished Worlds 2.0.1-1.17.1
		chickendropfeathers: Chicken Drop Feathers 1.0
		cleancut: CleanCut 1.17-4.0-fabric
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v5 5.0.38
		collective-fabric: Collective (Fabric) 1.62
		com_electronwill_night-config_core: core 3.6.3
		com_electronwill_night-config_toml: toml 3.6.3
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		companion_bats: Companion Bats 1.18.4
		compostable-rottenflesh: Compostable Rotten Flesh 1.0.0
		connectiblechains: Connectible Chains 1.2.3
		continuity: Continuity 1.0.2+1.17
		cool_elytra: Cool Elytra 1.3.0
		copperarmorandtools: Copper Armor & Tools 1.4.5
		cotton-config: Cotton Config 1.0.0-rc.7
		cotton-logging: Cotton Logging 1.0.0-rc.4
		couplings: Couplings 1.5.0+1.17
		cpas: cpas 2.0.1
		cpas-api: cpas-api 2.0.1
		cpas-runtime: cpas-runtime 2.0.1
		cpas-trinkets: cpas-trinkets 2.0.1
		craftablechainmail: Craftable Chainmail Armor 1.17.1-1.0.0-[FABRIC]
		craftablehorsearmour: Craftable Horse Armour & Saddle [CHA&S] 1.6-Fabric
		craftabletotemofundying: Craftable Totem Of Undying 1.17.1-1.0.0-[FABRIC]
		crawl: Crawl 0.9.3
		ctm: ConnectedTexturesMod for Fabric 0.5.1+1.17
		cullleaves: Cull Leaves 2.3.0
		customstars: Custom Stars 0.5
		damagetilt: Damage Tilt 1.17-fabric-0.1.2
		damagetint: Damage tint 1.1.0
		dataattributes: Data Attributes 1.0.6
		day_dream: Day Dream 1.0.3
		dcch: DCCH 1.0
		deepslatecutting: Deepslate Cutting 1.2.1
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.3
		doggomod: Doggo Mod 1.0.2
		doublejump: Double Jump Mod 1.0.1+mc1.17
		drinkbeer: Drink Beer 2.3
		dsurround: §6Dynamic Surroundings§r: §eFabric Edition 0.0.2
		dynamicsoundfilters: Dynamic Sound Filters 1.2.0+1.17.1
		eatinganimationid: Eating Animation 1.2
		editsign: EditSign 2.2.2
		elytratrinket: Elytra Trinket 2.0.1-1.17
		enderitemod: Enderite Mod 1.2.5
		endgoblintraders: End Goblin Traders 1.3.0
		endless_cake: Endless Cake 1.0.0
		enhanced_attack_indicator: Enhanced Attack Indicator 1.0.2+1.17
		escaperope: Escape Rope 1.1.3
		expandability: ExpandAbility 4.0.2
		explorerscompass: Explorer's Compass 1.17.1-2.0.0-fabric
		extractpoison-fabric: Extract Poison (Fabric) 1.5
		extrasounds: Extra Sounds 1.4.1
		fabric: Fabric API 0.42.1+1.17
		fabric-api-base: Fabric API Base 0.4.0+5847535018
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.1+5847535018
		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.2+5847535018
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.6+5847535018
		fabric-command-api-v1: Fabric Command API (v1) 1.1.4+5847535018
		fabric-commands-v0: Fabric Commands (v0) 0.2.3+5847535018
		fabric-containers-v0: Fabric Containers (v0) 0.1.13+5847535018
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.3.1+5847535018
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.6+5847535018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.13+5847535018
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.3.1+5847535018
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.11+5847535018
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.2+5847535018
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.8+5847535018
		fabric-item-api-v1: Fabric Item API (v1) 1.2.5+5847535018
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.1+5847535018
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.5+5847535018
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.3+5847535018
		fabric-language-kotlin: Fabric Language Kotlin 1.6.5+kotlin.1.5.31
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.5+5847535018
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.5+5847535018
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.2+6d0fac4218
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.5+6d0fac4218
		fabric-models-v0: Fabric Models (v0) 0.3.1+5847535018
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.14+5847535018
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.12+5847535018
		fabric-networking-v0: Fabric Networking (v0) 0.3.3+5847535018
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.11+6d0fac4218
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.5+6d0fac4218
		fabric-particles-v1: Fabric Particles (v1) 0.2.5+5847535018
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.13+5847535018
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.5+5847535018
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.9+5847535018
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.6+6d0fac4218
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.6+5847535018
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.2.1+6d0fac4218
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.7+6d0fac4218
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.1+6d0fac4218
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.9+5847535018
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.5+5847535018
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.9+5847535018
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.14+5847535018
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.2+5847535018
		fabric-textures-v0: Fabric Textures (v0) 1.0.7+5847535018
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.1+eb76084f18
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.1+6d0fac4218
		fabricloader: Fabric Loader 0.12.5
		fabricshieldlib: Fabric Shield Lib 1.4.5+1.17
		fake-player-api: Fake Player API 0.2.0
		fallingleaves: Falling Leaves 1.7.4+1.17.1
		fallingtree: FallingTree 2.12.2
		fastdecay: FastDecay 1.0.0
		fasttransferlib: Fast Transfer Lib 0.5.6
		feather_trampling: Feather Trampling 1.0.0
		fiber: fiber 0.23.0-2
		flesh2leather: Flesh2Leather 1.0.2
		flytre_lib: FlytreLib 0.2.21
		forgottenrecipes: Forgotten Recipes 1.0.3
		fortune-gives-experience: Fortune Gives Experience 1.1.0
		geckolib3: Geckolib 3.0.11
		goblintraders: Goblin Traders 1.3.0
		goosiklib: Goosik Lib 0.1.0
		grindenchantments: Grind Enchantments 1.4.0+1.17.1
		guild: Guild 0.3.3
		helpwanted: Help Wanted 1.1.2
		herdspanic: Herds Panic 1.0.3
		hologram-api: Hologram API 0.2.1+1.17.1
		horsebanners: Horse Banners 1.0.0
		identity: Identity 1.15.2-1.17.1
		indium: Indium 1.0.0+mc1.17.1
		indypets: Independent Pets 0.5.0
		iris: Iris 1.1.2-starline+build.460
		itemscroller: Item Scroller 0.15.0-dev.20210707.005506
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 16
		justmobheads-fabric: Just Mob Heads (Fabric) 5.0
		kirin: Kirin UI 1.9.1
		konkrete: Konkrete 1.3.0
		lambdynlights: LambDynamicLights 2.0.1+1.17
		lcsl: Colored Sea Lanterns 1.0.0
		leather-blocks: Leather Blocks 1.1.2
		lengthyladders: Lengthy Ladders 1.0.5
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 4.1.3+1.17.1
		libninepatch: LibNinePatch 1.1.0
		lithium: Lithium 0.7.3
		maelstrom_library: Maelstrom Library 1.2.2-1.17.1
		malilib: MaLiLib 0.10.0-dev.24
		mavm: More Axolotl Variants Mod 1.0.2b
		maybe-data: Maybe data 1.0.1-1.17
		midnightlib: MidnightLib 0.2.9
		mighty_mangoes: Mighty Mangoes 1.0.5
		minecraft: Minecraft 1.17.1
		mm: Manningham Mills 2.3
		mo_glass: Mo Glass 1.5-MC1.17.1
		modmenu: Mod Menu 2.0.4
		more-structures-add-on-for-william-wythers-overhauled-overworld: More Structures add-on for William Wythers Overhauled Overworld 1.2
		morebannerfeatures: More Banner Features 1.0.7
		morevillagers-fabric: MoreVillagersFabric 2.1.1-SNAPSHOT
		morevillagesmod: More Villages Mod 1.0.0
		mousewheelie: Mouse Wheelie 1.7.3+mc1.17.1-pre1
		multipart_entities: MultipartEntities 1.1.3-1.17.1
		musketmod: Musket Mod 1.3.0
		mythic-mounts: Mythic Mounts 1.17.1-2.0
		namepain: Name Pain 1.4.0
		naturescompass: Nature's Compass 1.17.1-2.0.1-fabric
		nauticality: Nauticality 0.1.2
		nears: Nears 1.1.2
		net_objecthunter_exp4j: exp4j 0.4.8
		nha: Netherite Horse Armor 1.3.1
		nightvisionflashbegone: Night Vision Flash be gone! 1.0.1
		noexpensive: NoExpensive 1.17-Fabric-1.2.0
		npcvariety: NPC Variety 2.2.0
		omega-config: OmegaConfig 1.0.8
		onsoulfire: On Soul Fire 1.17-3
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.31
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.0
		org_openjdk_nashorn_nashorn-core: nashorn-core 15.3
		oxidized: Oxidized 1.5.0
		packet_tweaker: Packet Tweaker 0.2.0+1.17.1
		particlerain: Particle Rain 1.5.0
		passable-leaves: Passable Leaves 2.0.1
		pettable: Pettable 1.2.0
		placeholder-api: Placeholder API 1.1.1+1.17.1
		plantable_pots: Plantable Flower Pots 1.1.0
		platinum: Platinum Mod 6.4.3
		playerabilitylib: Pal 1.3.0-nightly.1.17-rc1
		playerex: PlayerEx 3.0.6
		polymer: Polymer 0.1.6+1.17.1
		polymorph: Polymorph 0.0.13-1.17.1
		powershot: Powershot 1.3.0-1.17-fabric
		presencefootsteps: Presence Footsteps r32-1.17-rc1
		puddles: Puddles 1.2.0
		quickspyglasser: Quick Spyglasser 0.2.2
		reeses-sodium-options: Reese's Sodium Options 1.2.0
		relicex: RelicEx 3.0.1
		rib: The Real Infinity Bow 1.1.0
		ricemod: Tarks Rice Mod 1.1.2
		roughlyenoughitems: Roughly Enough Items 6.0.264-alpha
		roundtrees: Round Trees 1.0.0
		satin: Satin 1.6.0-nightly.1.17-pre3
		schonkysheep: Chonky Sheep 1.0.0
		sculkblocks: Sculk Blocks 1.0.0
		secondchance: Second Chance 1.2.0
		server_translations_api: Server Translations API 1.4.5+1.17
		sgui: SGui 1.0.0-rc4+1.17.1
		silkthatamethyst: Silk That Amethyst 1.0.0
		silktouch_spawners: SilkTouch Spawners 0.0.1
		skinlayers: 3d Skin Layers 1.2.1
		slime_sling: SlimeSling 1.0.0
		smart-recipes: Smart Recipes 0.1.0+1.17
		smoothblocks: Smooth Blocks 1.2.4
		smoothboot: Smooth Boot 1.16.5-1.6.0
		sodium: Sodium 0.3.0+IRIS2-build.114
		sodium-extra: Sodium Extra 0.3.5
		soulsegg: Souls Egg 2.1.0+1.17.1
		spidersproducewebs-fabric: Spiders Produce Webs (Fabric) 1.5
		spill: Spill 1.0.0
		spruceui: SpruceUI 3.2.0+1.17
		squirrels: Squirrels 1.2.0-1.17
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stoneholm: Stoneholm 1.3
		stonevaults: Stonevaults 1.1.0
		strawgolem: Strawgolem 1.10-B5
		survivalisland: Survival Island 0.1.5
		sync: Sync (Fabric) 1.2
		team_reborn_energy: Energy 0.1.1
		the_bumblezone: The Bumblezone - Fabric 3.3.1+1.17.1
		the_loved_ones: The Loved Ones 1.2.0+1.17
		thonkutil: ThonkUtil 1.2
		travelersbackpack: Traveler's Backpack 1.17.1-6.0.0
		trident_return: TridentReturn 1.2.4
		trinkets: Trinkets 3.0.4
		tweed: Tweed 3.0.0-beta.26
		universal-graves: Universal Graves 1.1.2+1.17.1
		unlimiteddragoneggs: Unlimited Dragon Eggs 1.2.1
		untitledduckmod: Untitled Duck Mod 0.3.0
		vanilla_degus: Vanilla Degus 1.2.3
		villagebellrecipe-fabric: Village Bell Recipe (Fabric) 1.3
		villagernames: Villager Names 2.0.1
		villagershats: Goosik's Villager Hats 1.2.0
		villainousfishai: Villainous Fish AI 1.0.1
		visuality: Visuality 0.1.3
		waveycapes: WaveyCapes 1.0.4
		waystones: Waystones 2.2.0
		weaponthrow: Weapon Throw 1.17.1-1.2
		wie: Water Imbued Enchantment & Thunder Imbued Enchantment 1.0.1
		william-wythers-overhauled-overworld: William Wythers Overhauled Overworld 1.7
		witherturnsskeletons: Wither turns Skeletons 1.0.0
		wolveswitharmor: Wolves With Armor 1.6.1-1.17.1
		yungsapi: YUNG's API 1.17-Fabric-19
	Launched Version: fabric-loader-0.12.5-1.17.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>

![imagen](https://user-images.githubusercontent.com/87394015/141527183-b5857260-dd3c-4ef3-9a28-33ce28a96a52.png)

**Comment by Motschen** [comment]
Yes, this mod is very outdated and unfinished.
I'll continue this after updating all of my mods for 1.18
